version: "2.30.1"
services:
  spring-api-image:
    image: spring-apicrud-image
    container_name: spring-apicrud-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - springcrud-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql_crud_database
    environment:
      MYSQL_ROOT_PASSWORD: andres123
      MYSQL_DATABASE: springcrud_db
      MYSQL_USER: andres
      MYSQL_PASSWORD: 210721
    ports:
      - "3307:3306"
    networks:
      - springcrud-network
    volumes:
      - mysql-volume:/var/lib/mysql

networks:
  springcrud-network:
volumes:
  mysql-volume:
